baseURL: https://www.robbarry.org/
languageCode: en-us
title: Rob Barry
theme: PaperMod
post: :slug/
page: :slug/
tags: "tag/:slug/"
paginate: 999999
relativeURLs: true

menu:
  main:
  - identifier: "about"
    name: "About"
    url: "/"
    weight: 1
  # - identifier: "work"
  #   name: "Work"
  #   url: "/work/"
  #   weight: 2
  - identifier: "articles"
    name: "Articles"
    url: "/categories/articles/"
    weight: 2
  - identifier: "videos"
    name: "Videos"
    url: "/categories/videos/"
    weight: 3
  - identifier: "audio"
    name: "Audio"
    url: "/categories/audio/"
    weight: 4
  - identifier: "thoughts"
    name: "Thoughts"
    url: "/posts/"
    weight: 5