baseURL: https://www.robbarry.org/
languageCode: en-us
title: Rob Barry
theme: PaperMod
post: :slug/
page: :slug/
tags: "tag/:slug/"
paginate: 999999
relativeURLs: true

menu:
  main:
  - identifier: "about"
    name: "About"
    url: "/"
    weight: 1
  - identifier: "stories"
    name: "Stories"
    url: "/categories/top/"
    weight: 2
  - identifier: "docsandpods"
    name: "Docs & Pods"
    url: "/categories/docsandpods/"
    weight: 3
  - identifier: "posts"
    name: "Posts"
    url: "/posts/"
    weight: 4    
  - identifier: "cv"
    name: "CV"
    url: "/assets/pdfs/rob-barry-resume.pdf"
    weight: 5
  # - identifier: "ai"
  #   name: "AI"
  #   url: "/posts/ai/"
  #   weight: 5
  # - identifier: "thoughts"
  #   name: "Thoughts"
  #   url: "/posts/"
  #   weight: 5